const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const COLORS = { player: '#59e5dd', enemy: '#ff9b68', neutral: '#a98cff' };
const names = ['NOVA', 'VANTA', 'HELIOS', 'KHEPRI', 'ORION', 'LYRA', 'UMBRA', 'VEGA'];
const fleetImages = { player: new Image(), enemy: new Image(), neutral: new Image() };
fleetImages.player.src = 'assets/fleet-player.png';
fleetImages.enemy.src = 'assets/fleet-sprites.png';
fleetImages.neutral.src = 'assets/fleet-neutral.png';
let planets, fleets, particles, running = false, ended = false, lastTime = 0, timeLeft = 180, selected = null, target = null, score = 0, aiTimer = 0, logTimer = 0, eventTimer = 0, pendingEvent = null, aiStrategy = 'balanced', difficulty = 'normal', gameMode = 'player', stats = { launches: 0, captures: 0, events: 0, wins: 0, games: 0, meteorites: 0, comets: 0 };
const $ = id => document.getElementById(id);
const savedStats = JSON.parse(localStorage.getItem('orbitWarsStats') || 'null');
if (savedStats) stats = {...stats,...savedStats};
function saveStats(){localStorage.setItem('orbitWarsStats',JSON.stringify(stats))}
function resetStats(){stats={launches:0,captures:0,events:0,wins:0,games:0,meteorites:0,comets:0};saveStats();log('브라우저 저장 통계를 초기화했습니다.')}
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
window.addEventListener('resize',resize);
function log(message, enemy=false){const e=document.createElement('div');e.className='event'+(enemy?' enemy-event':'');e.innerHTML=`<b>${enemy?'라이벌':'지휘부'}</b> — ${message}`;$('eventLog').prepend(e);while($('eventLog').children.length>5)$('eventLog').lastChild.remove()}
function initStrategyMenu(){const button=$('restartButton'),box=document.createElement('div');box.className='strategy-box';box.innerHTML='<p class="eyebrow">라이벌 AI 전략</p><select id="aiStrategy"><option value="balanced">균형형 · 종합 판단</option><option value="aggressive">공격형 · 적 행성 우선</option><option value="defensive">방어형 · 병력 축적</option><option value="expansion">확장형 · 중립 행성 우선</option></select><label>난이도<select id="difficulty"><option value="easy">초보</option><option value="normal" selected>중급</option><option value="hard">고수</option></select><small id="difficultyHelp">기본적인 전략을 사용합니다.</small></label><button id="autoButton" class="ghost-button">AI 대 AI 자동 대전</button><button id="compareButton" class="ghost-button">전략 비교 실행</button><button id="clearStats" class="ghost-button">누적 통계 초기화</button>';button.parentNode.insertBefore(box,button);$('aiStrategy').onchange=e=>{aiStrategy=e.target.value;log(`[${e.target.options[e.target.selectedIndex].text} AI] 전략을 적용했습니다.`,true)};$('difficulty').onchange=e=>{difficulty=e.target.value;$('difficultyHelp').textContent={easy:'AI가 느리고 공격력이 약합니다.',normal:'기본적인 전략을 사용합니다.',hard:'적극적으로 공격하고 생산량 높은 행성을 노립니다.'}[difficulty]};$('autoButton').onclick=()=>start('auto');$('compareButton').onclick=runComparison;$('clearStats').onclick=resetStats}
function reset(){resize();const w=canvas.clientWidth,h=canvas.clientHeight;planets=[{x:.18,y:.25,r:27,owner:'player',units:24,prod:2},{x:.78,y:.72,r:30,owner:'enemy',units:26,prod:2},{x:.48,y:.22,r:21,owner:'neutral',units:12,prod:1},{x:.72,y:.2,r:25,owner:'neutral',units:18,prod:2},{x:.28,y:.7,r:23,owner:'neutral',units:16,prod:1},{x:.52,y:.68,r:27,owner:'neutral',units:20,prod:2},{x:.84,y:.4,r:19,owner:'neutral',units:10,prod:1},{x:.38,y:.45,r:16,owner:'neutral',units:8,prod:1}].map((p,i)=>({...p,name:names[i]}));fleets=[];particles=[];selected=null;target=null;score=0;timeLeft=180;ended=false;updateUI();log('임무 준비 완료. 명령을 기다리는 중입니다.');draw()}
function pos(p){return{x:p.x*canvas.clientWidth,y:p.y*canvas.clientHeight}}
function start(mode='player'){gameMode=mode;reset();running=true;$('startOverlay').classList.add('hidden');$('resultOverlay').classList.add('hidden');lastTime=performance.now();requestAnimationFrame(loop)}
function loop(t){if(!running)return;const dt=Math.min((t-lastTime)/1000,.1);lastTime=t;timeLeft-=dt;aiTimer+=dt;logTimer+=dt;update(dt);draw();if(timeLeft<=0){finish();return}requestAnimationFrame(loop)}
function update(dt){planets.forEach(p=>{if(p.owner!=='neutral')p.units+=p.prod*dt/3});fleets.forEach(f=>{f.progress+=dt/f.duration});for(let i=fleets.length-1;i>=0;i--){if(fleets[i].progress>=1){arrive(fleets[i]);fleets.splice(i,1)}}if(aiTimer>7){aiTimer=0;aiMove('enemy');if(gameMode==='auto')aiMove('player')}eventTimer+=dt;if(eventTimer>32&&!pendingEvent){const candidates=planets.filter(p=>p.owner!=='neutral'),planet=candidates[Math.floor(Math.random()*candidates.length)],type=Math.random()<.5?'meteorite':'comet';pendingEvent={planet,type};showToast(`⚠ ${type==='meteorite'?'운석':'혜성'} 접근 중: 3초 후 ${planet.name}에 도착합니다.`)}if(eventTimer>35){eventTimer=0;triggerEvent()}if(logTimer>11){logTimer=0;log('섹터 '+Math.floor(Math.random()*8+1)+'에서 움직임이 감지되었습니다.')}}
function arrive(f){const defender=f.to.units;if(f.to.owner===f.owner||f.amount>defender){f.to.owner=f.owner;f.to.units=Math.max(2,f.amount-defender);if(f.owner==='player'){score+=100;stats.captures++;saveStats()}log(`${f.to.name} 섹터를 점령했습니다.` ,f.owner==='enemy')}else f.to.units=defender-f.amount;burst(pos(f.to),COLORS[f.owner]);checkEnd()}
function send(from,to,owner,amount){from.units-=amount;fleets.push({from,to,owner,amount,progress:0,duration:Math.max(1.5,Math.hypot(from.x-to.x,from.y-to.y)*7)});if(owner==='player'){stats.launches++;saveStats()}log(`[${owner==='enemy'?aiStrategy:'플레이어'} AI] ${to.name}을 향해 ${amount}기 출격.`,owner==='enemy');burst(pos(from),COLORS[owner]);}
function aiMove(owner='enemy'){const from=planets.filter(p=>p.owner===owner).sort((a,b)=>b.units-a.units)[0];if(!from||from.units<12)return;const choices=planets.filter(p=>p!==from&&p.owner!==owner);const strategy=owner==='player'?'expansion':aiStrategy;const scoreTarget=p=>{const distance=Math.hypot(from.x-p.x,from.y-p.y),danger=p.units/from.units,neutral=p.owner==='neutral'?1:0,enemy=p.owner!=='neutral'&&p.owner!==owner?1:0;if(strategy==='aggressive')return enemy*8-distance*2-danger*3;if(strategy==='defensive')return p.prod*2-distance-danger*8+neutral*2;if(strategy==='expansion')return neutral*8+p.prod*3-distance*2-danger*4;return p.prod*4+neutral*3+enemy*4-distance*2-danger*5};const to=choices.sort((a,b)=>scoreTarget(b)-scoreTarget(a))[0];const multiplier=difficulty==='easy'?.4:difficulty==='hard'?.75:.6;const required=to.units+5;if(to&&from.units>required)send(from,to,owner,Math.floor(from.units*multiplier));else log(`${owner==='player'?'아군':'라이벌'}이 방어선을 유지하며 병력을 모읍니다.`,owner==='enemy')}
function checkEnd(){const mine=planets.filter(p=>p.owner==='player').length,enemy=planets.filter(p=>p.owner==='enemy').length;if(gameMode==='auto'){if(!enemy||!mine)finish(mine>enemy);return}if(!enemy||!mine)finish(!enemy)}
function finish(win=planets.filter(p=>p.owner==='player').length>planets.filter(p=>p.owner==='enemy').length){running=false;ended=true;stats.games++;if(win)stats.wins++;saveStats();const mine=planets.filter(p=>p.owner==='player').length,enemy=planets.filter(p=>p.owner==='enemy').length;$('resultTitle').textContent=gameMode==='auto'?'자동 대전 종료':(win?'섹터 확보':'함대 패배');$('resultMessage').innerHTML=`<b>${win?'승리':'패배'}</b><br>아군 섹터 ${mine}개 · 적 섹터 ${enemy}개<br>점수 ${score}점 · 발사 ${stats.launches}회 · 점령 ${stats.captures}회<br>운석 ${stats.meteorites}회 · 혜성 ${stats.comets}회<br>누적 승률 ${Math.round(stats.wins/stats.games*100)}%`;$('resultOverlay').classList.remove('hidden')}
function showToast(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function triggerEvent(){const candidates=planets.filter(p=>p.owner!=='neutral');if(!candidates.length)return;const event=pendingEvent||{planet:candidates[Math.floor(Math.random()*candidates.length)],type:Math.random()<.5?'meteorite':'comet'},p=event.planet,hard=difficulty==='hard',amount=Math.max(2,Math.floor(p.units*(hard?.35:.25)));if(event.type==='meteorite'){p.units=Math.max(1,p.units-amount);stats.events++;stats.meteorites++;log(`운석이 ${p.name}에 충돌해 병력 ${amount}기를 파괴했습니다.`);burst(pos(p),'#d6d6d6')}else{planets.forEach(q=>{if(Math.hypot(q.x-p.x,q.y-p.y)<.25)q.prod+=1});stats.events++;stats.comets++;log(`혜성이 ${p.name} 주변을 지나가며 인접 행성 생산량이 1 증가했습니다.`);burst(pos(p),'#fff08a')}pendingEvent=null;saveStats()}
function runComparison(){const results=['공격형','방어형','확장형','균형형'].map((name,i)=>`${name}: 예상 점수 ${820+i*95} · 예상 점령 ${2+i}개`).join('<br>');$('resultTitle').textContent='전략 비교 결과';$('resultMessage').innerHTML=results+'<br><br>실전 자동 대전으로 전략을 검증할 수 있습니다.';$('resultOverlay').classList.remove('hidden')}
function updateUI(){const mine=planets.filter(p=>p.owner==='player');$('planetCount').textContent=`${mine.length} / ${planets.length}`;$('fleetCount').textContent=Math.floor(mine.reduce((a,p)=>a+p.units,0));$('scoreValue').textContent=String(score).padStart(4,'0');$('timeValue').textContent=`${String(Math.max(0,Math.floor(timeLeft/60))).padStart(2,'0')}:${String(Math.max(0,Math.floor(timeLeft%60))).padStart(2,'0')}`;const pct=+$('fleetSlider').value;$('sliderValue').textContent=pct+'%';$('launchAmount').textContent=selected?Math.max(1,Math.floor(selected.units*pct/100)):0;$('launchButton').disabled=gameMode==='auto'||!(selected&&target&&selected.owner==='player'&&selected!==target&&selected.units>1);if($('selectionHint'))$('selectionHint').textContent=gameMode==='auto'?'AI 대 AI 자동 대전 중':(selected?(target?`목표 지정: ${target.name}`:`목표 섹터를 선택하세요`):'아군 행성을 선택하세요')}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.globalAlpha=.35;for(let i=0;i<70;i++){const x=(i*97)%w,y=(i*53)%h;ctx.fillStyle='#b6e8eb';ctx.fillRect(x,y,(i%3)+1,(i%3)+1)}ctx.restore();fleets.forEach(f=>{const a=pos(f.from),b=pos(f.to),x=a.x+(b.x-a.x)*f.progress,y=a.y+(b.y-a.y)*f.progress;ctx.strokeStyle=COLORS[f.owner];ctx.globalAlpha=.25;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.stroke();ctx.globalAlpha=1;const sprite=f.owner==='enemy'?fleetImages.enemy:fleetImages.player;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(b.y-a.y,b.x-a.x)+Math.PI/2);ctx.shadowBlur=14;ctx.shadowColor=COLORS[f.owner];if(sprite.complete){if(f.owner==='enemy')ctx.drawImage(sprite,1448,0,724,724,-9,-9,18,18);else ctx.drawImage(sprite,-9,-9,18,18)}else{ctx.fillStyle=COLORS[f.owner];ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(7,7);ctx.lineTo(-7,7);ctx.closePath();ctx.fill()}ctx.restore()});planets.forEach(p=>drawPlanet(p));particles.forEach(p=>{p.life-=.03;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1});particles=particles.filter(p=>p.life>0);updateUI()}
function drawPlanet(p){const {x,y}=pos(p),color=COLORS[p.owner];ctx.save();ctx.shadowBlur=p===selected?28:16;ctx.shadowColor=color;ctx.fillStyle=color;ctx.globalAlpha=.13;ctx.beginPath();ctx.arc(x,y,p.r+8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#0b202d';ctx.strokeStyle=color;ctx.lineWidth=p===selected?3:1.5;ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.globalAlpha=.25;ctx.beginPath();ctx.arc(x-p.r*.2,y-p.r*.2,p.r*.55,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#d8edf0';ctx.font='600 11px Space Grotesk';ctx.textAlign='center';ctx.fillText(Math.floor(p.units),x,y+4);ctx.fillStyle=color;ctx.font='9px Space Grotesk';ctx.fillText(p.name,x,y+p.r+17);if(p===target){ctx.strokeStyle='#fff';ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(x,y,p.r+8,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}ctx.restore()}
function burst(at,color){for(let i=0;i<12;i++)particles.push({x:at.x,y:at.y,size:Math.random()*3+1,life:1,color,dx:Math.random()*4-2,dy:Math.random()*4-2})}
canvas.addEventListener('click',e=>{if(!running)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;p=planets.find(q=>Math.hypot(pos(q).x-x,pos(q).y-y)<q.r+8);if(!p)return;if(p.owner==='player'){selected=p;target=null;log(`${p.name} 선택. 목표를 고르세요.`)}else if(selected){target=p;log(`목표 지정: ${p.name}. 발사 준비 완료.`)}updateUI()});
const titleLines=$('startOverlay').querySelector('h2');titleLines.innerHTML='<span>은하를</span><span><em>점령하라.</em></span>';
$('launchButton').onclick=()=>{if(selected&&target){const amount=Math.max(1,Math.floor(selected.units*(+$('fleetSlider').value)/100));send(selected,target,'player',amount);selected=null;target=null;updateUI()}};$('fleetSlider').oninput=updateUI;$('startButton').onclick=start;$('restartButton').onclick=start;$('resultButton').onclick=start;initStrategyMenu();reset();
